language: python
python:
- 3.7
services:
- docker
before_install:
- docker pull quay.io/pypa/manylinux2010_x86_64
script:
- docker run --rm -e PLAT=manylinux2010_x86_64 -e PYPI_TOKEN=$PYPI_TOKEN -v `pwd`/requirements.txt:/io/requirements.txt
  -v `pwd`:/io quay.io/pypa/manylinux2010_x86_64:latest /io/build_wheels.sh
deploy:
  provider: pypi
  distributions: sdist
  skip_existing: true
  user: __token__
  password:
    secure: onb+HyMV/YJ9hJMFh6HYXjdLLukZrDDVfvinlkwAP9yFv/Apw2jduhyCw9YTaP7KRUkpCwXcWBxLEnw+DY0LSrMwcURmKIh0YNMqkWy9FmwXTL9c/VRt3eq7MexkFjTF/oaVHIhDEMunyNTxxai2aAay1rnbbkewLZnPmVgwTsMjoSD6SA1gLEaHfIeWssl8JuNoejeUtbR5hUtNKHOhj1BmwdHTm9N2fKnBdeG+WWxm9aNZnPtRQ7U0i/H73/jn7Nmr78h9qAFpkhd+VFCgkFQnApb+gXLxG+mJ9OrDuP6ilmjHwE/PVeJQlJmZWwoFxl8pLhmkQ1LOWkB5OVpP+5UpXbb+ysBS4nU7fM9pMhjF9k+0fpIZf/6j2nOzHmrUI2UT7lnxDDjNpPlPy3acthfl6UD2w0b0Z4DqYyyaTbVkXWRqPqB5rbKQvofOOIXCv9NZXbf+QcdZSq0QrtWNfvo6Ut4KfOw3PyIAQqCXGDvEiGJ0gfkQ7yZVeVQN1N0m78ubmwNJ4/TS+NvXmdMfFmMu3NicO1IVmXkYT5ng5cBn8WD6Vl2VTGJ0ZN/F3Q1CGX9FzBwQCVV83lCRbqmW0oUD0ceWjPTIMFKqaKz4gMuNo/7HCkEcrow+DCIqCDCv7xF17ouNX4QknJ5vOLZ3xpYfvLeABaUHiNYJxITbb/Q=
  on:
    tags: true
    repo: dimitern/xmlstarlet
    python: 3.7
env:
  global:
    secure: gDyvq82h6Xo8bYue4Yp73DJQNi9qCNQw1qwUPaZT38iUH+9B28GXPr5NWXpZHkO7IcGi4omXwZgxtSTB89bugfMfRu8Ce43uLVCGybB0f13cbNmn0j0xMcT3L1Zmjvj97fhCcF5oaEtXpWC0tgU04U5HSMNSU+UZpARZjSWrBFUgt5STZU0vy9eP/bkUC6u1H83KyM15scpIcPu65vKiZ3xNBLheLpo3j/HFu+IELjZBdXGsii1tuGFOActhirAWDQgzP7ecCvbLxAYAl2+p4sH4RzG5NuliRRaD0Q1sPrxmHkG7F41QWeWQ35kBBkRj756TQL317Pd9Y9/b8xXp7tsPZH/6sYsBoF3YNIkMSSsLK8xXRE8eHTP28LVcsT2IKjEoCw+jPLTVPce6fBs9e04iOYshHO+KVqIAmGotnN+rwKl3hfDtPFT0xQCw00yTRBz5YHhMHSKZMYtsxsRRcTwF1HGUOvOwfjwMQi2w4LMMP5XYZJfoSATmNzDvZvh1mZaJh6iDP3d9vlysXYfEklpSB1Qwa1BSNuNI2YC4Btrox2SJ+0aGRbdsCLHpPHCkAG8TAcSAxPRUgATEJRib6rG94no/Rr7Oe+Lnb/4BODJ851shMv4nNQCHOsNeQm7jz9v5FXqS0wXlczZFaNArMlzh7vtLFDWAMmCFfH2e38o=
